// The MakeReady user guide, as browsable Help Center articles.
//
// GENERATED — do not edit by hand. The guide is written in
// scripts/generate_user_guide.py, which emits this file alongside the
// Markdown and Word versions so all three say the same thing.
// Regenerate: pnpm guide:shots && python scripts/generate_user_guide.py

import type { HelpArticle } from "./content";

export const USER_GUIDE_SECTION = "User Guide";

export const USER_GUIDE_ARTICLES: HelpArticle[] = [
  {
    slug: "guide-overview",
    title: "How the job runs, and how to find your way around",
    section: USER_GUIDE_SECTION,
    order: 0,
    summary: "What this guide covers, how to sign in, and how the navigation, search and dashboard fit together.",
    who: "Everyone",
    related: ["guide-the-job-on-one-page"],
    blocks: [
      { k: "p", text: "MakeReady is where the whole business now runs: the enquiry, the quote, the order, the art, the press, the invoice, the money in, the money out, and the books. This guide walks that whole path in the order the work actually happens, and for every step it says which screen you do it on." },
      { k: "p", text: "Read Part 1 for the shape of the job on one page. Part 2 is the step-by-step, with a picture of each screen as it looks today. Part 3 is the daily, weekly and monthly rhythm. Part 4 covers admin and permissions." },
      { k: "tip", text: "Every screenshot in this guide is generated from the live application. When a screen changes, the pictures are re-captured rather than redrawn, so what you see here is what you will see when you sign in." },
      { k: "h", text: "Getting in" },
      { k: "p", text: "Sign in at the MakeReady address with your work email and password. If your account is new, you will have been sent an invitation link to set your own password — nobody, including an administrator, can see it." },
      { k: "img", src: "guide/01-login.png", caption: "The sign-in screen." },
      { k: "p", text: "Second-factor security lives under your own account, at Account → Security. You can register an authenticator app, a passkey or security key, and print recovery codes for the day your phone is flat." },
      { k: "img", src: "guide/e7-security.png", caption: "Account → Security: authenticator app, passkeys, recovery codes." },
      { k: "h", text: "Finding your way around" },
      { k: "list", items: ["The left-hand menu is the whole platform. One section opens at a time — opening Accounting closes CRM — so the list stays short enough to read.", "The search box at the top searches everything at once: customers, contacts, invoices, bills, vendors, stock items and designs. Type a company name, an invoice number or a SKU.", "The dashboard is the landing page: open quotes, open orders, jobs on the floor, low stock, your pipeline and your own open tasks, with shortcuts to the things you start most often."] },
      { k: "img", src: "guide/02-dashboard.png", caption: "The dashboard — what is open right now, and the quick actions." },
      { k: "img", src: "guide/03-search.png", caption: "Search finds customers, contacts, invoices, bills, vendors, stock and designs together." },
      { k: "list", items: ["Notifications collects what the platform needs to tell you — a proof approved, an approval waiting, a job that has moved."] },
      { k: "img", src: "guide/04-notifications.png", caption: "Notifications." },
    ],
  },
  {
    slug: "guide-the-job-on-one-page",
    title: "The job on one page",
    section: USER_GUIDE_SECTION,
    order: 1,
    summary: "The whole path from a phone call to a closed month, and the screen each stage happens on.",
    who: "Everyone",
    related: ["guide-overview", "guide-take-in-the-enquiry"],
    blocks: [
      { k: "p", text: "This is the whole path from a phone call to money in the bank and a closed month. Each row is a stage; the right-hand column is where you do it." },
      { k: "table", headers: ["#", "What happens", "Where in MakeReady"], rows: [["1", "An enquiry arrives; you record who it is", "CRM → Business Partners / Pipeline"], ["2", "Set the account up: terms, credit, contract pricing", "CRM → the customer → Account details, Contract pricing"], ["3", "Price it and send the quote", "Sales → Quotes → New quote → Quote Builder"], ["4", "They say yes; the quote becomes an order", "Sales → Quotes → Convert; then Sales → Orders"], ["5", "Art is briefed, drawn, proofed and approved", "Art Department → the request"], ["6", "Blanks are bought and received", "Inventory → Purchase Orders; Accounting → GRNI"], ["7", "The job is scheduled, printed and checked", "Production → Schedule; Quality"], ["8", "It ships and you invoice it", "The order → Create invoice; Accounting → Invoices"], ["9", "The money comes in and is banked", "Accounting → Payments → Deposits"], ["10", "Slow payers are chased", "Accounting → Collections, Aging, Statements"], ["11", "Suppliers, staff and expenses are paid", "Accounting → Bills, Payment Runs, Expenses, Payroll"], ["12", "The month is closed and reported", "Accounting → Periods, Close, Financial Statements"], ["13", "You check how the business is doing", "Accounting → Flash, Quarterly; Controlling; Reports"]] },
      { k: "tip", text: "Every order carries an Order journey strip showing exactly which of these stages it has reached. If you only ever learn one thing about an order, learn to read that strip." },
    ],
  },
  {
    slug: "guide-take-in-the-enquiry",
    title: "Step 1 — Take in the enquiry",
    section: USER_GUIDE_SECTION,
    order: 2,
    summary: "Recording a new lead, working the pipeline, and scanning a business card instead of typing it.",
    who: "Sales",
    related: ["guide-the-job-on-one-page", "guide-set-up-the-account"],
    blocks: [
      { k: "p", text: "Everyone you deal with — lead, prospect or customer — is a Business Partner. CRM lists them all, filtered by stage, by owner, or down to just your own accounts." },
      { k: "img", src: "guide/10-crm-list.png", caption: "CRM → Business Partners. Filter by stage or to My accounts." },
      { k: "p", text: "The Pipeline is the same information as a board, so you can see what is moving." },
      { k: "img", src: "guide/11-crm-pipeline.png", caption: "Pipeline — leads, prospects and customers as columns." },
      { k: "h", text: "Adding someone new" },
      { k: "steps", items: [{ text: "CRM → New Business Partner." }, { text: "Fill in the account, the primary contact, the address and the terms." }, { text: "Save. They start as a Lead; promote them to Prospect and then Customer as the relationship moves." }] },
      { k: "p", text: "If you are holding their business card, press Scan instead of typing: photograph the card and the details are read off it and filled in for you to check." },
      { k: "img", src: "guide/12-crm-new.png", caption: "New Business Partner — or scan a business card and let it fill itself in." },
    ],
  },
  {
    slug: "guide-set-up-the-account",
    title: "Step 2 — Set the account up properly",
    section: USER_GUIDE_SECTION,
    order: 3,
    summary: "The customer record, logging contact, contract pricing, and spotting accounts due to reorder.",
    who: "Sales",
    related: ["guide-take-in-the-enquiry", "guide-quote-it"],
    blocks: [
      { k: "p", text: "The customer page is the single place everything about an account lives: details, contacts, addresses, order history, open financial documents, tasks and the full activity log." },
      { k: "img", src: "guide/13-customer.png", caption: "A customer record — details, contacts, history, financials and activity in one place." },
      { k: "list", items: ["Log a call, an email or a visit with the buttons at the top — that is what feeds the rep activity report, so it is worth doing.", "AI summary reads the account's history and tells you where things stand before you ring them.", "Draft email writes a first draft you then edit; it is never sent without you sending it.", "Invite to portal gives the customer their own login to see orders, proofs and invoices.", "New Quote starts a quote with this customer already selected."] },
      { k: "h", text: "Contract pricing" },
      { k: "p", text: "Where a customer has negotiated pricing — a percentage off, or a fixed price per unit — record it once here and the quote builder applies it automatically for everyone who quotes them." },
      { k: "img", src: "guide/14-customer-pricing.png", caption: "Contract pricing — agreed discounts applied automatically at quoting time." },
      { k: "h", text: "Customers who are due to come back" },
      { k: "p", text: "Reorder radar lists accounts whose usual reorder interval has passed. It will draft the outreach for you and start the quote." },
      { k: "img", src: "guide/15-reorders.png", caption: "Reorder radar — who is overdue to reorder, with the outreach half-written." },
    ],
  },
  {
    slug: "guide-quote-it",
    title: "Step 3 — Quote it",
    section: USER_GUIDE_SECTION,
    order: 4,
    summary: "Building a quote in the Quote Builder, and the design and catalog libraries behind it.",
    who: "Sales",
    related: ["guide-set-up-the-account", "guide-turn-win-into-order"],
    blocks: [
      { k: "p", text: "The Quote Builder replaces the Excel order forms. Pick the customer and the product template, and the pricing runs inside the app." },
      { k: "img", src: "guide/20-quote-new.png", caption: "New quote — choose the customer and the product template, then open the builder." },
      { k: "steps", items: [{ text: "Add a line and pick the item." }, { text: "Type the quantity — the unit price fills in from the quantity band." }, { text: "Pick the size for apparel; the upcharge is added automatically." }, { text: "Tick the charges and setup that apply — screen prep, mid-run colour changes, art time, rush." }, { text: "Set Reorder on a repeat job and the new-only screen prep drops off." }, { text: "Send it, and watch it in the quote list." }] },
      { k: "img", src: "guide/21-sales-hub.png", caption: "Sales → Quotes. Every quote, its product, status and value." },
      { k: "tip", text: "Unit prices on band-priced items are deliberately locked — the same reason the grey cells on the old spreadsheets said 'Formulas – Do Not Type'. For a genuine one-off, set the line to custom and type your own price." },
      { k: "p", text: "Two libraries sit behind the builder. The Design Library holds every customer design with its item numbers and barcodes; the Catalog holds the garment styles, their costs and the decoration pricing rules." },
      { k: "img", src: "guide/22-designs.png", caption: "Design Library — customer designs, catalog numbers and barcodes." },
      { k: "img", src: "guide/23-catalog.png", caption: "Administration → Catalog & Pricing — the styles and the pricing rules behind every quote." },
    ],
  },
  {
    slug: "guide-turn-win-into-order",
    title: "Step 4 — Turn the win into an order",
    section: USER_GUIDE_SECTION,
    order: 5,
    summary: "Converting a quote, and using the order page as the spine of the whole job.",
    who: "Sales",
    related: ["guide-quote-it", "guide-art-and-proofing"],
    blocks: [
      { k: "p", text: "An accepted quote converts straight into a sales order — nothing is re-keyed." },
      { k: "img", src: "guide/30-orders.png", caption: "Sales → Orders, each showing the stage it has reached." },
      { k: "p", text: "The order page is the spine of the job. Everything that happens to it hangs off here." },
      { k: "img", src: "guide/31-order.png", caption: "A sales order — journey, stage, art, production, items, fulfilment and invoicing." },
      { k: "list", items: ["Order journey across the top shows how far the job has got.", "Update stage moves it on: Order Received → Art & Proof → In Production → Quality Check → Shipped → Delivered.", "Submit to art raises the art request; Send to production puts it on the floor.", "Items & decoration is the specification the artist and the press both work from.", "Customer tracker link is a public link you can send so they can follow the job themselves without ringing you.", "Create invoice raises the invoice from the order when it ships."] },
    ],
  },
  {
    slug: "guide-art-and-proofing",
    title: "Step 5 — Art and proofing",
    section: USER_GUIDE_SECTION,
    order: 6,
    summary: "The art queue, the brief, revisions, the readiness checklist, and getting the proof approved.",
    who: "Art",
    related: ["guide-turn-win-into-order", "guide-buy-the-blanks"],
    blocks: [
      { k: "p", text: "Everything submitted to art lands in the art department queue, as a board or a list." },
      { k: "img", src: "guide/40-art-queue.png", caption: "The art queue." },
      { k: "p", text: "An art request walks a fixed path, and the buttons enforce it in order." },
      { k: "img", src: "guide/41-art-job.png", caption: "An art request — brief, artist, revisions, readiness checklist and proofing." },
      { k: "steps", items: [{ text: "Assign artist." }, { text: "Artwork produced." }, { text: "Out for review." }, { text: "Customer approved — the proof goes to the customer from this screen, and every proof sent is kept." }, { text: "Production ready — this one only unlocks once the readiness checklist is complete." }] },
      { k: "list", items: ["Draft brief with AI writes the customisation brief from the order specification; the artist edits it.", "Production files & handoff is where the press-ready files go.", "Revisions keeps every version, so 'which one did they approve?' always has an answer."] },
      { k: "p", text: "The artist schedule shows who is working on what, and what is unassigned." },
      { k: "img", src: "guide/42-art-schedule.png", caption: "Artist schedule — workload and anything unassigned." },
      { k: "p", text: "Logos, photographs and brand assets live in the Content Library rather than on somebody's desktop." },
      { k: "img", src: "guide/43-content-library.png", caption: "Content Library — the shared asset store." },
    ],
  },
  {
    slug: "guide-buy-the-blanks",
    title: "Step 6 — Buy the blanks",
    section: USER_GUIDE_SECTION,
    order: 7,
    summary: "The item master, the reorder forecast, raising and receiving purchase orders, and GRNI.",
    who: "Purchasing",
    related: ["guide-art-and-proofing", "guide-make-it"],
    blocks: [
      { k: "p", text: "The item master holds every stocked item with its on-hand quantity, reorder point and cost across the warehouses." },
      { k: "img", src: "guide/50-inventory.png", caption: "Inventory — the item master, on hand and reorder points." },
      { k: "p", text: "The reorder forecast does the thinking: it looks at usage, lead time and what is on hand, and tells you what to order and how many days you have left." },
      { k: "img", src: "guide/53-forecast.png", caption: "Reorder forecast — what to buy, and how long before you run out." },
      { k: "steps", items: [{ text: "Inventory → Purchase Orders → New PO, pick the vendor and the lines." }, { text: "Receive the goods against the PO when they arrive." }, { text: "Match the vendor's bill to the receipt." }] },
      { k: "img", src: "guide/51-purchase-orders.png", caption: "Purchase orders — ordered, expected, received and value." },
      { k: "p", text: "Anything received but not yet invoiced by the vendor sits in GRNI, aged, so nothing is quietly missing from the accounts at month end." },
      { k: "img", src: "guide/54-grni.png", caption: "Goods received, not invoiced — receipts still waiting on a vendor bill." },
    ],
  },
  {
    slug: "guide-make-it",
    title: "Step 7 — Make it",
    section: USER_GUIDE_SECTION,
    order: 8,
    summary: "The production schedule, quality inspections, and equipment work orders.",
    who: "Production",
    related: ["guide-buy-the-blanks", "guide-invoice-it"],
    blocks: [
      { k: "p", text: "The production schedule is the ship calendar and the board of what is on the floor." },
      { k: "img", src: "guide/60-production-schedule.png", caption: "Production schedule — the ship calendar." },
      { k: "p", text: "Quality inspections are recorded against the order, with what was inspected, what was rejected and the result." },
      { k: "img", src: "guide/62-quality.png", caption: "Quality — inspections against orders." },
      { k: "p", text: "Equipment problems and servicing go on work orders so the press that keeps jamming is a record, not a rumour." },
      { k: "img", src: "guide/63-maintenance.png", caption: "Maintenance work orders." },
    ],
  },
  {
    slug: "guide-invoice-it",
    title: "Step 8 — Invoice it",
    section: USER_GUIDE_SECTION,
    order: 9,
    summary: "Raising the invoice from the order, emailing it, and the customer pay link.",
    who: "Finance",
    related: ["guide-make-it", "guide-get-the-money-in"],
    blocks: [
      { k: "p", text: "Invoices are normally raised from the order with Create invoice, so the lines and the customer come across already correct. Accounting → Invoices → New invoice is there for anything standalone." },
      { k: "img", src: "guide/70-invoices.png", caption: "Invoices, filtered by status — draft, sent, partial, paid, void." },
      { k: "img", src: "guide/72-invoice-new.png", caption: "Accounting → Invoices → New invoice, for anything not raised from an order." },
      { k: "img", src: "guide/71-invoice.png", caption: "An invoice — lines, payments, PDF and email." },
      { k: "list", items: ["PDF produces the document; Email invoice sends it to the customer.", "The emailed invoice carries a pay link: the customer can pay by ACH with no fee, or by card with the surcharge shown, without ringing anyone.", "Record payment takes a receipt straight against this invoice.", "Void reverses an invoice raised in error. Invoices are never deleted — the number stays, marked void, so the sequence has no holes."] },
    ],
  },
  {
    slug: "guide-get-the-money-in",
    title: "Step 9 — Get the money in",
    section: USER_GUIDE_SECTION,
    order: 10,
    summary: "Receipts, deposits, aging, the collections call list, statements and credit memos.",
    who: "Finance",
    related: ["guide-invoice-it", "guide-pay-everyone-else"],
    blocks: [
      { k: "p", text: "Cash comes in two steps, deliberately: you record the receipt when it arrives, then bank it in a batch. The bank statement shows the batch, not the individual cheques, which is what makes the reconciliation work." },
      { k: "img", src: "guide/80-payments.png", caption: "Payments — every receipt, and the on-account box for cash you cannot yet match." },
      { k: "steps", items: [{ text: "Record the receipt. Against one invoice, across several, or on account if you do not yet know what it pays." }, { text: "Bank it. Accounting → Deposits batches the undeposited receipts into the deposit you actually take to the bank." }] },
      { k: "img", src: "guide/81-deposits.png", caption: "Deposits — undeposited receipts, ready to batch." },
      { k: "h", text: "Chasing what is late" },
      { k: "p", text: "The aging report is the overall picture: everything owed, by customer, by how late it is." },
      { k: "img", src: "guide/82-aging.png", caption: "AR Aging — current, 1–30, 31–60, 61–90 and 90+." },
      { k: "p", text: "Collections is the working screen — the call list for the day rather than a report to read." },
      { k: "img", src: "guide/83-collections.png", caption: "Collections — today's call list, cards to run, prepay and COD, and the parent-account rollup." },
      { k: "list", items: ["Call list — 15 days past due is who to ring today.", "Cards to run today and Cards past due are the card-on-file accounts.", "Prepay / COD outstanding is work that should not have shipped without money.", "Open AR by parent account rolls the chains up, so a group with forty stores is one conversation."] },
      { k: "p", text: "A statement is what you send when they ask 'what do we actually owe?' — every open item and the aging summary, as a PDF or straight to their inbox." },
      { k: "img", src: "guide/84-statement.png", caption: "A customer statement — open items and aging, ready to email." },
      { k: "h", text: "Credits" },
      { k: "p", text: "A return, a shortage or an allowance is a credit memo. It sits open against the account until it is applied to invoices, exactly like a receipt." },
      { k: "img", src: "guide/85-credit-memos.png", caption: "Credit memos — raised, and what is still unapplied." },
      { k: "p", text: "Where an order would push a customer over their credit limit or is on hold, it goes to credit requests for a decision rather than being shipped on hope." },
      { k: "img", src: "guide/86-credit-requests.png", caption: "Credit requests — over-limit and on-hold orders awaiting approval." },
    ],
  },
  {
    slug: "guide-pay-everyone-else",
    title: "Step 10 — Pay everyone else",
    section: USER_GUIDE_SECTION,
    order: 11,
    summary: "Vendor bills, payment runs, vendor credits, staff expenses and payroll.",
    who: "Finance",
    related: ["guide-get-the-money-in", "guide-close-the-month"],
    blocks: [
      { k: "p", text: "Vendor bills are entered against the vendor and coded to the GL accounts they belong to." },
      { k: "img", src: "guide/90-bills.png", caption: "Bills — what is owed, what is due, and what is left on each." },
      { k: "img", src: "guide/91-bill.png", caption: "A bill — its lines, the accounts they are coded to, and its payments." },
      { k: "p", text: "Bills are not paid one at a time. A payment run selects everything due, gets it approved, and produces one instrument per vendor and one journal entry for the batch." },
      { k: "img", src: "guide/92-payment-runs.png", caption: "A payment run — everything due, netted against vendor credits, one payment per vendor." },
      { k: "p", text: "Credits from vendors are recorded so they net off the next run instead of being forgotten." },
      { k: "img", src: "guide/93-vendor-credits.png", caption: "Vendor credits." },
      { k: "h", text: "Staff expenses" },
      { k: "p", text: "Expense claims are entered as a report, submitted, approved, and then paid like any other bill. The screen tells you which GL account each category books to, so coding is not guesswork." },
      { k: "img", src: "guide/94-expenses.png", caption: "Expense reports, and what each category books to." },
      { k: "h", text: "Payroll" },
      { k: "p", text: "Payroll is posted twice a month from a template, so the same dozen-odd lines are not retyped. Start a run, check the figures, post it. The accrual run copies the last payroll rather than the last accrual, so accruals never drift." },
      { k: "img", src: "guide/95-payroll.png", caption: "Payroll journals — runs and the semi-monthly template." },
    ],
  },
  {
    slug: "guide-close-the-month",
    title: "Step 11 — Close the month",
    section: USER_GUIDE_SECTION,
    order: 12,
    summary: "Fiscal periods, the close, the ledger, financial statements, bank reconciliation and sales tax.",
    who: "Finance",
    related: ["guide-pay-everyone-else", "guide-see-how-youre-doing"],
    blocks: [
      { k: "p", text: "The Accounting hub is the index of everything in this part of the business." },
      { k: "img", src: "guide/a0-accounting-hub.png", caption: "The Accounting hub." },
      { k: "p", text: "The financial year runs October to September and is named for the year it ends in — FY2026 is October 2025 to September 2026. Each period is open, closing or locked." },
      { k: "img", src: "guide/a1-periods.png", caption: "Fiscal periods — status, entry counts and postings for every month of the year." },
      { k: "table", headers: ["Status", "What it means"], rows: [["Open", "Anyone with the right to post can post into it."], ["Closing", "Only the finance team can post — the month is being finished."], ["Locked", "Nothing can post. The month is done."]] },
      { k: "p", text: "The close screen walks the month: what is still outstanding, then lock it. A locked period can be reopened if something genuinely has to change, and that reopening is recorded." },
      { k: "img", src: "guide/a2-close.png", caption: "Period close — what is outstanding, then lock the month." },
      { k: "h", text: "The books themselves" },
      { k: "list", items: ["Journal Entries — every posting, whether it came from an invoice, a payment run, payroll or somebody's manual adjustment. Accruals reverse themselves automatically the following month.", "Trial Balance — every account's balance, debits equal to credits.", "Income Statement, Balance Sheet and Cash Flow — run for any date range, print or save as PDF."] },
      { k: "img", src: "guide/a3-journal.png", caption: "Journal entries — every posting and where it came from." },
      { k: "img", src: "guide/a4-trial-balance.png", caption: "Trial balance." },
      { k: "img", src: "guide/a5-income-statement.png", caption: "Income statement." },
      { k: "img", src: "guide/a6-balance-sheet.png", caption: "Balance sheet." },
      { k: "img", src: "guide/a7-cash-flow.png", caption: "Cash flow statement." },
      { k: "h", text: "Bank reconciliation" },
      { k: "p", text: "Import the bank statement, tick off what has cleared, and post anything the bank knows about that the books do not — charges, interest, fees." },
      { k: "img", src: "guide/a8-reconcile.png", caption: "Bank reconciliation — import the statement and clear the lines." },
      { k: "h", text: "Sales tax" },
      { k: "p", text: "The filing report gives you the period's figures by jurisdiction, where tax is being collected, and which customers hold exemption certificates." },
      { k: "img", src: "guide/a9-sales-tax.png", caption: "Sales tax filing, by jurisdiction, with exemption certificates." },
    ],
  },
  {
    slug: "guide-see-how-youre-doing",
    title: "Step 12 — See how the business is doing",
    section: USER_GUIDE_SECTION,
    order: 13,
    summary: "Weekly flash, the quarterly pack, segment P&L, goals, commission and job-level profit.",
    who: "Managers",
    related: ["guide-close-the-month", "guide-reports"],
    blocks: [
      { k: "p", text: "Weekly flash is the Monday-morning screen: cash position, the week's sales, the biggest receipts and invoices, and everything sitting waiting on somebody." },
      { k: "img", src: "guide/b0-flash.png", caption: "Weekly flash — the week at a glance, including cash not yet banked and credits not applied." },
      { k: "p", text: "Quarterly pack is the board version: the quarter against last year, year to date, the quarter by segment, and the cash and receivables behind it." },
      { k: "img", src: "guide/b1-quarterly.png", caption: "Quarterly pack." },
      { k: "p", text: "P&L by segment splits the result by the part of the operation that earned it — heat transfer, softgoods, embroidery, screen print, the warehouse, and the overhead departments." },
      { k: "img", src: "guide/b2-segment-pnl.png", caption: "P&L by segment." },
      { k: "p", text: "Sales goals sets each rep's monthly target and shows actual against it for the year." },
      { k: "img", src: "guide/b3-goals.png", caption: "Sales goals against actuals, by rep and month." },
      { k: "p", text: "Commission works out what each rep has earned on what has actually been invoiced." },
      { k: "img", src: "guide/b4-commission.png", caption: "Commission report." },
      { k: "h", text: "Job-level profit" },
      { k: "p", text: "Controlling asks the harder question: did this job, this customer, this rep actually make money?" },
      { k: "img", src: "guide/b5-job-costing.png", caption: "Job costing — revenue, cost and margin per order." },
      { k: "img", src: "guide/b6-profitability.png", caption: "Profitability by customer and by salesperson." },
      { k: "img", src: "guide/b7-budget.png", caption: "Budget against actual, account by account." },
    ],
  },
  {
    slug: "guide-reports",
    title: "Step 13 — Reports",
    section: USER_GUIDE_SECTION,
    order: 14,
    summary: "The built-in reports, and building, saving and scheduling your own.",
    who: "Everyone",
    related: ["guide-see-how-youre-doing", "guide-web-store"],
    blocks: [
      { k: "p", text: "Reports has two halves: the standard reports that are built in, and custom reports anyone can build and save." },
      { k: "img", src: "guide/c0-reports.png", caption: "The report catalogue — built-in reports and saved custom reports." },
      { k: "p", text: "The built-in set covers the reports the business has always run:" },
      { k: "list", items: ["Sales Analysis by Salesperson & Customer — three years side by side, month by month.", "Open Orders by Salesperson and by Type.", "Customer Credit Report — the credit picture for an account.", "Revenue Trend, Top Products & Designs, Sales-Rep Activity, Lead-Source ROI."] },
      { k: "img", src: "guide/c2-sales-analysis.png", caption: "Sales Analysis — three years by month, per customer, grouped by rep." },
      { k: "img", src: "guide/c3-credit-report.png", caption: "The Customer Credit Report." },
      { k: "img", src: "guide/c4-open-orders.png", caption: "Open Orders by Salesperson." },
      { k: "img", src: "guide/c5-rep-activity.png", caption: "Sales-Rep Activity — calls, notes, emails, visits, quotes and what they won." },
      { k: "h", text: "Building your own" },
      { k: "steps", items: [{ text: "Reports → Build a report." }, { text: "Pick the source and the columns." }, { text: "Add filter for each condition you want." }, { text: "Preview, then Save report." }] },
      { k: "img", src: "guide/c1-report-new.png", caption: "The report builder." },
      { k: "p", text: "A saved report can be edited, deleted, exported to CSV and scheduled to email itself out." },
    ],
  },
  {
    slug: "guide-web-store",
    title: "Step 14 — The web store",
    section: USER_GUIDE_SECTION,
    order: 15,
    summary: "Publishing products, pricing and promotions, and the orders that come in through the storefront.",
    who: "Sales",
    related: ["guide-reports", "guide-the-rhythm"],
    blocks: [
      { k: "p", text: "The web store is our own storefront — it replaces Zoey rather than talking to it. Products are published from the same inventory the rest of the platform uses, so there is one catalogue, not two." },
      { k: "img", src: "guide/d0-web-store.png", caption: "Web Store administration — products, retail and B2B pricing, visibility." },
      { k: "list", items: ["Add from inventory publishes an existing stocked item to the store.", "Categories, Promos and Groups control how it is presented and who sees what price.", "Customers and Orders are the store's own accounts and their orders."] },
      { k: "img", src: "guide/d1-web-store-orders.png", caption: "Store orders — pending, confirmed, fulfilled, cancelled." },
      { k: "img", src: "guide/d2-storefront.png", caption: "The storefront as a customer sees it." },
    ],
  },
  {
    slug: "guide-the-rhythm",
    title: "The rhythm of the job",
    section: USER_GUIDE_SECTION,
    order: 16,
    summary: "What to check every day, every week, twice a month, every month and every quarter.",
    who: "Everyone",
    related: ["guide-web-store", "guide-running-the-place"],
    blocks: [
      { k: "list", items: ["Dashboard — what is open, what is on the floor, what is low on stock.", "Collections → call list — ring today's 15-days-past-due accounts; run the cards that are due.", "Payments — record what came in.", "Art queue and Production schedule — anything stuck, anything due to ship.", "Approvals inbox — decisions waiting on you."] },
      { k: "h", text: "Every week" },
      { k: "list", items: ["Weekly flash — the week's cash, sales, receipts and anything waiting on someone.", "Deposits — bank the receipts; nothing should sit undeposited over a weekend.", "Payment run — pay the bills that are due, netted against vendor credits.", "Reorder forecast — order the blanks before the days-left column goes red.", "GRNI — chase vendor bills for goods already received."] },
      { k: "h", text: "Twice a month" },
      { k: "list", items: ["Payroll — start the run from the template, check it, post it."] },
      { k: "h", text: "Every month" },
      { k: "steps", items: [{ text: "Bank reconciliation — import the statement and clear it." }, { text: "Sales tax filing — run the period and file it." }, { text: "GRNI and accruals — make sure costs sit in the month that earned them." }, { text: "Trial balance — check it balances and nothing looks wrong." }, { text: "Income statement, balance sheet, cash flow — run and save them." }, { text: "Period close — work the close screen, then lock the month." }] },
      { k: "h", text: "Every quarter" },
      { k: "list", items: ["Quarterly pack — the quarter against last year, by segment.", "Sales goals and Commission — how the reps did, and what they earned.", "Profitability and job costing — which customers and which work are actually worth having."] },
    ],
  },
  {
    slug: "guide-running-the-place",
    title: "Running the place",
    section: USER_GUIDE_SECTION,
    order: 17,
    summary: "User accounts, teams, report permissions, workflows, approvals, settings and the audit trail.",
    who: "Administrators",
    related: ["guide-the-rhythm", "guide-what-came-from-sap"],
    blocks: [
      { k: "p", text: "Administration → Users is where accounts are created. Create user & send invite emails them a link to set their own password — you never handle it." },
      { k: "img", src: "guide/e1-users.png", caption: "Administration → Users — roles, status, last login." },
      { k: "list", items: ["Edit changes someone's roles.", "Force reset makes them set a new password next time they sign in.", "Activate / deactivate turns access on and off. Deactivating ends their sessions immediately."] },
      { k: "tip", text: "Thirteen of the sales reps carried over from SAP were created inactive with no password (the other three already had accounts). Check each address is right, then activate and invite them — nothing is sent until you do." },
      { k: "p", text: "Teams group people for routing — art, product, production, purchasing, sales — so work reaches the right desk rather than a named individual who might be on holiday." },
      { k: "img", src: "guide/e2-teams.png", caption: "Teams and routing groups." },
      { k: "h", text: "Who can see which report" },
      { k: "p", text: "Reports → Access controls visibility. A built-in report can be restricted so only granted roles or people see it; a saved report is private, shared, or open to everyone, with grants on top." },
      { k: "img", src: "guide/c6-report-access.png", caption: "Report access — restrict a built-in report, or grant view, edit and delete." },
      { k: "table", headers: ["Right", "What it allows"], rows: [["View", "Open the report and export it."], ["Edit", "Change its columns, filters, sharing and scheduled delivery."], ["Delete", "Remove it entirely."]] },
      { k: "p", text: "Rights do not cascade upward: a view grant never confers edit, and edit never confers delete." },
      { k: "h", text: "Workflows and approvals" },
      { k: "p", text: "One-click workflows do the repetitive sequences — onboarding a new customer, for example — in one action instead of six screens. Approval rules decide what needs a human yes before it proceeds; those decisions queue in the approvals inbox." },
      { k: "img", src: "guide/e3-workflows.png", caption: "Workflows — one-click sequences and recent runs." },
      { k: "img", src: "guide/e4-approvals.png", caption: "The approvals inbox." },
      { k: "h", text: "Settings and the audit trail" },
      { k: "p", text: "Configuration holds the company details and the document number series — the prefix and next number for each document type." },
      { k: "img", src: "guide/e6-config.png", caption: "Configuration — company settings and document numbering." },
      { k: "p", text: "The audit log records who did what, to which record, from which address. It is searchable and exports to CSV." },
      { k: "img", src: "guide/e5-audit.png", caption: "The audit log." },
    ],
  },
  {
    slug: "guide-what-came-from-sap",
    title: "What came across from SAP",
    section: USER_GUIDE_SECTION,
    order: 18,
    summary: "The history and open balances migrated from SAP, and why old document numbers still work.",
    who: "Everyone",
    related: ["guide-running-the-place"],
    blocks: [
      { k: "p", text: "MakeReady was not started empty. The SAP history was migrated, so the reports have real history behind them from the first day:" },
      { k: "table", headers: ["What", "How much"], rows: [["Customers and vendors", "7,100+ business partners, 833 vendors"], ["Order history", "262,000 historical orders"], ["Stocked items", "6,219 items across four warehouses"], ["General ledger", "Full posted history; ties to SAP within a penny"], ["Open receivables", "1,978 invoices, $2,050,117.68"], ["Open credits", "97 credit memos, $17,044.11"], ["Open payables", "1,095 bills, $703,428.68"], ["Payment terms", "56 terms, mapped to the customers that use them"], ["Sales reps", "16 reps, linked to their user accounts"]] },
      { k: "p", text: "Invoices carried over keep their SAP number with an SI- prefix, credit memos SC-, and vendor bills SAP-, so a customer or supplier quoting an old document number can still be found. Their balances were carried without re-posting to the ledger, because the ledger already holds that history — which is why the accounts tie exactly rather than double-counting." },
      { k: "h", text: "Getting help" },
      { k: "p", text: "The Help section in the left-hand menu holds the how-to articles. Anything that looks wrong in the data — rather than in the way a screen works — is worth raising with an administrator, who can check the audit log to see exactly what happened and when." },
    ],
  },
];
